CREATE TABLE usuarios (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	idade INTEGER NOT NULL,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE tickets (
	id SERIAL PRIMARY KEY, 
	nome VARCHAR(50) NOT NULL,
	descricao VARCHAR(150) NOT NULL,
	canal VARCHAR(80) NOT NULL,
	status ENUM("Pendente", "Em Processo", "Concluído", "Cancelado") NOT NULL,
	prioridade ENUM("Baixa", "Média", "Alta") NOT NULL,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)